stages:
  - lint
  - build
  - release

linting:
  variables:
    GOLANGCI_LINT_VERSION: '2.4.0'
  image: ${GITLAB_DEPENDENCY_PROXY}golangci/golangci-lint:v$GOLANGCI_LINT_VERSION
  tags: [docker]
  stage: lint
  before_script:
    - go mod tidy
  script:
    - golangci-lint run --output.text.path=stdout --output.text.colors=false --output.text.print-issued-lines=false --output.code-climate.path=gl-code-quality-report.json
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json
  allow_failure: false

buildproject:
  image: docker.io/golang:alpine
  tags: [docker]
  stage: build
  before_script:
    - apk update --no-cache
    - apk add --no-cache make zip
    - go mod tidy
  script:
    - make release 


